server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    instance:
      prefer-id-address: true
      instance-id: microservice-CRUD8020
mybatis:
  mapper-locations: classpath:mapping/*.xml
#  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.demo.entity
#  提取实体类所在包名